Repository TokTok/dockerfiles, pull requests merged in 2022-02, with the labels that each got.

#82 cleanup: Remove need for pipefail.
  buildfarm/builder/Dockerfile
  infer/Dockerfile
Labels: cleanup

#83 fix: Fix build context passing in docker buildx.
  .github/workflows/docker.yml
Labels: bug

#84 fix: Checkout code in toolchain build.
  .github/workflows/docker.yml
Labels: bug

#85 perf: Use docker buildx for ghc builds.
  .github/workflows/docker.yml
Labels: performance

#86 chore: Add msgpack to infer/compcert images.
  compcert/Dockerfile
  infer/Dockerfile
Labels: chore

#87 chore: Add msgpack to freebsd image.
  .github/workflows/docker.yml
  freebsd/src/cmake-freebsd-run.sh
  freebsd/src/setup-vm
  freebsd/src/setup-vm.expect
Labels: chore

#88 fix: Fix Flutter SDK version being assumed to be 0.0.0-unknown
  flutter/web/Dockerfile
Labels: bug

#89 feat: Add haskell image for use in CI builds.
  .github/workflows/docker.yml
  .hadolint.yaml
  haskell/Dockerfile
  haskell/stack.yaml
Labels: enhancement

#92 chore: Install all toktok haskell packages into the haskell image.
  .gitignore
  haskell/Dockerfile
  haskell/stack.yaml
Labels: chore

#93 chore: Install our haskell packages from git, not stack.
  haskell/Dockerfile
  haskell/stack.yaml
Labels: chore

#95 chore: Fix one more extra dep.
  haskell/stack.yaml
Labels: chore

#97 chore: Split haskell image.
  haskell/Dockerfile
  haskell/stack.yaml
Labels: chore

#98 chore: Move STACK_ROOT out of HOME.
  haskell/Dockerfile
Labels: chore

#99 perf: Pre-build toktok-stack haskell dependencies.
  haskell/Dockerfile
Labels: performance

#100 feat: Add bazel-cache docker image.
  .github/workflows/docker.yml
  buildfarm/cache/Dockerfile
Labels: enhancement

#101 feat: Add toxchat/nacl image to speed up the nacl build in c-toxcore.
  .github/workflows/docker.yml
  nacl/Dockerfile
  nacl/install-nacl.sh
Labels: enhancement
