Repository TokTok/dockerfiles, pull requests merged in 2024-12, with the labels that each got.

#173 chore: Support Android 7 (API 24).
  qtox/docker/Dockerfile.android-builder
  qtox/docker/Dockerfile.windows-builder
Labels: chore

#174 chore: Build the debug version of Qt for Android.
  .github/workflows/docker.yml
  qtox/docker/Dockerfile.android-builder
Labels: chore

#175 chore: Update to jdk17 in the docker base image.
  bazel/Dockerfile
  bazel/arion-compose.nix
Labels: chore

#176 chore: Add ubsan runtime library to fedora build.
  qtox/docker/Dockerfile.fedora
Labels: chore

#177 chore: Add armeabi-v7a builder image for qTox.
  .github/workflows/docker.yml
  qtox/docker/Dockerfile.android-builder
Labels: chore

#178 chore: Add support for Android 7 in qTox.
  .github/workflows/docker.yml
  qtox/docker/Dockerfile.android-builder
  qtox/docker/Dockerfile.host-qt
Labels: chore

#179 chore: Add ccache to qtox builder images.
  qtox/docker/Dockerfile.alpine
  qtox/docker/Dockerfile.android-builder
  qtox/docker/Dockerfile.archlinux
  qtox/docker/Dockerfile.debian
  qtox/docker/Dockerfile.fedora
  qtox/docker/Dockerfile.flatpak-builder
  qtox/docker/Dockerfile.host-qt
  qtox/docker/Dockerfile.ubuntu-lts
  qtox/docker/Dockerfile.windows-builder
Labels: chore

#181 chore: Add missing tls plugins for qTox windows build.
  qtox/docker/Dockerfile.windows-builder
Labels: chore

#182 feat: Add builder image for fully static qtox.
  .github/workflows/docker.yml
  .restyled.yaml
  qtox/build_qt_linux.sh
  qtox/build_static_qtox.sh
  qtox/clang-pc-fixer
  qtox/docker/Dockerfile.alpine-static
  qtox/toolchain/linux-static-toolchain.cmake
Labels: enhancement

#183 cleanup: Don't use cross compilation for static Qt.
  .github/workflows/docker.yml
  qtox/clang-pc-fixer
  qtox/docker/Dockerfile.alpine-static
  qtox/toolchain/linux-static-toolchain.cmake
Labels: cleanup

#184 fix: Add wine32 and wine64 to the qtox windows docker images.
  qtox/docker/Dockerfile.windows-builder
Labels: bug

#186 cleanup: Remove linuxdeployqt and other unused deps.
  qtox/build_ldqt_linux.sh
  qtox/build_qt_linux.sh
  qtox/docker/Dockerfile.ubuntu-lts
  qtox/download/download_ldqt.sh
Labels: cleanup

#189 fix: Add missing deps in ubuntu-lts image.
  qtox/docker/Dockerfile.ubuntu-lts
Labels: bug

#187 feat: Add macOS Qt builder script.
  qtox/build_qt_macos.sh
Labels: enhancement

#185 chore: Add option to build some qtox deps as static lib.
  qtox/build_ffmpeg.sh
  qtox/build_libexif.sh
  qtox/build_openal.sh
  qtox/build_openssl.sh
  qtox/build_opus.sh
  qtox/build_qrencode.sh
  qtox/build_qt_macos.sh
  qtox/build_sodium.sh
  qtox/build_sqlcipher.sh
  qtox/build_toxcore.sh
  qtox/build_utils.sh
  qtox/build_vpx.sh
Labels: chore

#188 cleanup: Don't install qttools unnecessarily.
  qtox/docker/Dockerfile.alpine-static
Labels: cleanup

#190 fix: Correct cmake root path in qt macos build script.
  qtox/build_qt_macos.sh
Labels: bug

#191 chore: Add sonnet to the qtox build scripts.
  .gitignore
  qtox/build_extra_cmake_modules.sh
  qtox/build_hunspell.sh
  qtox/build_qt_macos.sh
  qtox/build_sonnet.sh
  qtox/build_toxcore.sh
  qtox/download/download_extra_cmake_modules.sh
  qtox/download/download_hunspell.sh
  qtox/download/download_sonnet.sh
Labels: chore

#192 chore: Build macOS static Qt with ubsan.
  qtox/build_qt_macos.sh
Labels: chore

#194 fix: Rename blake2b symbols in libsodium to avoid conflict with Qt.
  qtox/build_sodium.sh
Labels: bug

#195 chore: Use latest OpenAL on macOS.
  qtox/build_ffmpeg.sh
  qtox/build_openal.sh
  qtox/download/download_openal.sh
Labels: chore

#197 chore: Add ccache to flatpak builder.
  qtox/docker/Dockerfile.flatpak-builder
Labels: chore

#198 chore: Use an ancient toxcore in qtox alpine build.
  qtox/docker/Dockerfile.alpine
Labels: chore

#199 chore: Update flatpak KDE SDK version to 6.8.
  qtox/docker/Dockerfile.flatpak-builder
  qtox/download/download_sodium.sh
Labels: chore

#201 docs: Add comment to explain why we use old toxcore.
  qtox/docker/Dockerfile.alpine
Labels: documentation

#200 chore: Downgrade to flatpak kde platform 6.7 again.
  qtox/docker/Dockerfile.flatpak-builder
Labels: chore

#202 chore: Also install kde platform into flatpak image.
  qtox/docker/Dockerfile.flatpak-builder
Labels: chore

#196 cleanup: Build Qt without OpenGL support.
  qtox/build_qt_macos.sh
  qtox/build_qt_windows.sh
  qtox/docker/Dockerfile.alpine-static
Labels: cleanup

#203 chore: Fix static qtox build.
  qtox/clang-pc-fixer
  qtox/download/download_sodium.sh
  qtox/download/download_sqlcipher.sh
  qtox/download/download_toxcore.sh
Labels: chore

#204 fix: Fix qtox static linux build (for real now).
  qtox/clang-pc-fixer
Labels: bug

#206 chore: update nix to 24.11
  bazel/Dockerfile
  bazel/arion-compose.nix
  bazel/arion-pkgs.nix
  bazel/build.sh
Labels: chore

#207 chore: dhcp networking
  bazel/Dockerfile
  bazel/arion-compose.nix
Labels: chore

#208 chore: Upgrade to bazel 7.
  bazel/arion-compose.nix
Labels: chore

#209 chore: add alsa pkgs to alpine for appimage
  qtox/docker/Dockerfile.alpine
Labels: chore

#210 chore: Make sure all dependencies are built with optimisation flags.
  qtox/build_extra_cmake_modules.sh
  qtox/build_ffmpeg.sh
  qtox/build_gdb_windows.sh
  qtox/build_glfw.sh
  qtox/build_gmp_windows.sh
  qtox/build_libexif.sh
  qtox/build_libexpat_windows.sh
  qtox/build_mingw_ldd_windows.sh
  qtox/build_mpfr_windows.sh
  qtox/build_nsisshellexecasuser_windows.sh
  qtox/build_openal.sh
  qtox/build_openssl.sh
  qtox/build_opus.sh
  qtox/build_qrencode.sh
  qtox/build_qt_macos.sh
  qtox/build_qt_windows.sh
  qtox/build_sodium.sh
  qtox/build_sonnet.sh
  qtox/build_sqlcipher.sh
  qtox/build_static_qtox.sh
  qtox/build_toxcore.sh
  qtox/build_toxcore_linux.sh
  qtox/build_utils.sh
  qtox/build_vpx.sh
Labels: chore

#211 cleanup: Speed up host-qt build.
  qtox/docker/Dockerfile.host-qt
Labels: cleanup

#213 chore: Add back qmake to host-qt image.
  qtox/docker/Dockerfile.android-builder
  qtox/docker/Dockerfile.host-qt
Labels: chore

#212 cleanup: Update qtox windows builder image to Qt 6.8.1.
  .github/workflows/docker.yml
  qtox/build_ffmpeg.sh
  qtox/build_glfw.sh
  qtox/build_qt_windows.sh
  qtox/build_toxcore.sh
  qtox/build_zstd.sh
  qtox/docker/Dockerfile.windows-builder
  qtox/download/download_ffmpeg.sh
  qtox/download/download_gdb.sh
  qtox/download/download_glfw.sh
  qtox/download/download_gmp.sh
  qtox/download/download_libexif.sh
  qtox/download/download_libexpat.sh
  qtox/download/download_mingw_debug_scripts.sh
  qtox/download/download_mingw_ldd.sh
  qtox/download/download_mpfr.sh
  qtox/download/download_nsisshellexecasuser.sh
  qtox/download/download_openssl.sh
  qtox/download/download_opus.sh
  qtox/download/download_qrencode.sh
  qtox/download/download_qt.sh
  qtox/download/download_vpx.sh
  qtox/download/download_zstd.sh
Labels: cleanup

#215 cleanup: Slightly nicer log messages by reducing file path length.
  qtox/build_qt_macos.sh
Labels: cleanup

#216 chore: Fixes for macOS SDK 15.2.
  qtox/build_sonnet.sh
Labels: chore

#217 chore: Build our own Qt 6.8.1 in the appimage build.
  qtox/build_extra_cmake_modules.sh
  qtox/build_qtbase_linux.sh
  qtox/build_qtimageformats_linux.sh
  qtox/build_qtsvg_linux.sh
  qtox/build_qttools_linux.sh
  qtox/build_qtwayland_linux.sh
  qtox/build_sonnet.sh
  qtox/build_toxcore_linux.sh
  qtox/build_utils.sh
  qtox/docker/Dockerfile.alpine-appimage
  qtox/download/download_qtbase.sh
  qtox/download/download_qtimageformats.sh
  qtox/download/download_qtsvg.sh
  qtox/download/download_qttools.sh
  qtox/download/download_qtwayland.sh
Labels: chore

#218 chore: Add backends to openal-soft so we can have sound.
  qtox/clang-pc-fixer
  qtox/docker/Dockerfile.alpine-static
Labels: chore

#219 fix: Build ffmpeg with xcb support for desktop capture.
  qtox/docker/Dockerfile.alpine-static
  qtox/pkg-config-static
Labels: bug

#221 chore: Upgrade minimum toxcore version to 0.2.14.
  qtox/docker/Dockerfile.alpine
Labels: chore
